### ISSUE TITLE
New Scala File command

### ISSUE THREAD

**Issue by ckipp01** [ckipp01/nvim-metals#2]
**Describe the feature**

One of my most-used features in coc-metals is the New Scala File command. This quickly allows you to create a `Trait`, `Object`, `Worksheet`, etc.

**Potential ways to implement?**

In order for this to work we'll need to figure out how to implement the [`metals/quickPick`](https://scalameta.org/metals/docs/editors/new-editor.html#metalsquickpick) extension.

**Search terms**

quickpick, New Scala File

**Comment by landerlo** [comment]
I can take this one on. I plan to support the UI extensions like quickPick, but before that I'm sending a PR to metals to extend the request to include optional name and symbol types so the interaction only happen when those are omitted. That makes API makes more sense on their side as both fields can be known beforehand, as the types will hardly change.

**Comment by ckipp01** [comment]
Hey! Sure, that'd be great! It's ironic you comment on this. I was playing around a bit with `inputlist()` this morning and _attempting_ to see if I was able to get a basic `window/showMessage` working. It will be sort of funny if the `metals/quickPick` ends up working before that.

**Comment by landerlo** [comment]
Great! I think we need to support those interactions but the NewFile feature shouldn't force the UI as it makes sense to provide the kind beforehand, the same way that name is optional because you might be doing a newSymbol quickfix. I envision having a list of symbols and being able to repeat command in vim doing repeating the NewFile using last provided kind value as well. Looking at metals now. It's a trivial change to make the kind optional so if passed in request picker is not invoked. That makes it a better API, hope they accept it.
Also the better API should be sending edits to the client so it doesn't do the filesystem interaction, e.g. server is remote, but I'm not sure if the server can initiate that. Anyway that's something for another time.

**Comment by ckipp01** [comment]
Closed via #12
